"""GENERATED by scripts/harness/compile_architecture.py from .harness/architecture.yaml.
Edit architecture.yaml and recompile; hand edits here will be overwritten.
"""
# Rule: harness_no_network_requests — forbids ['requests', 'httpx', 'urllib3'] in layer 'harness'
from __future__ import annotations
import pathlib
import re
import sys

FORBIDDEN = ['requests', 'httpx', 'urllib3']
GLOBS = ['scripts/harness/**']
RULE_ID = 'harness_no_network_requests'

def main() -> int:
    root = pathlib.Path.cwd()
    pat = re.compile(r'(?:^|\b)(?:import|from)\s+(' + '|'.join(re.escape(n) for n in FORBIDDEN) + r')\b')
    violations: list[str] = []
    seen: set[pathlib.Path] = set()
    def _files(p: pathlib.Path):
        if p.is_file():
            yield p
        elif p.is_dir():
            yield from p.rglob('*')
    for glob in GLOBS:
        for match in root.glob(glob):
            for path in _files(match):
                if not path.is_file() or path in seen:
                    continue
                seen.add(path)
                try:
                    text = path.read_text(encoding='utf-8')
                except (OSError, UnicodeDecodeError):
                    continue
                for lineno, line in enumerate(text.splitlines(), 1):
                    if pat.search(line):
                        violations.append(f"{path}:{lineno}: {line.strip()}")
    if violations:
        print(f"arch-leash: rule {RULE_ID} violated:")
        for v in violations:
            print(f"  {v}")
        return 1
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
