"""Compile .harness/architecture.yaml into gates and check scripts.

Deterministic. No model calls. Re-runnable: every run produces the same
output for the same input. Files emitted carry a GENERATED header so the
compiler knows what it owns; gate lines carry `# arch-leash:<id>` so
removed rules can be pruned cleanly.

Check scripts are emitted as Python (.py) so cycle_done.py — which runs
gates through `subprocess.call(cmd, shell=True)` — can execute them on
Windows, macOS, and Linux without a shell dependency on PATH.
"""
from __future__ import annotations
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent))
from scripts.harness.validate_architecture import (
    Architecture,
    Pattern,
    parse_architecture,
)

GENERATED_HEADER_PY = (
    '"""GENERATED by scripts/harness/compile_architecture.py from .harness/architecture.yaml.\n'
    "Edit architecture.yaml and recompile; hand edits here will be overwritten.\n"
    '"""\n'
)

GENERATED_HEADER_INI = (
    "; GENERATED by scripts/harness/compile_architecture.py from .harness/architecture.yaml\n"
    "; Edit architecture.yaml and recompile; hand edits here will be overwritten.\n"
)


def _detect_python(root: pathlib.Path) -> bool:
    return (root / "pyproject.toml").exists() or (root / "setup.py").exists()


def _layer_module_root(layer_paths: tuple[str, ...]) -> str:
    """Derive a Python dotted package from a glob like 'src/myapp/domain/**'.

    v1: only the first non-empty path is used. Multi-glob layers are a known
    limitation.
    """
    for p in layer_paths:
        parts = [seg for seg in p.replace("\\", "/").split("/") if seg and seg != "**"]
        if parts and parts[0] == "src":
            parts = parts[1:]
        if parts:
            return ".".join(parts)
    return ""


def _emit_importlinter_ini(arch: Architecture) -> str:
    allowed: dict[str, set[str]] = {l.name: set() for l in arch.layers}
    for edge in arch.allowed_dependencies:
        allowed[edge.src].update(edge.dst)
    names = [l.name for l in arch.layers]
    forbidden_pairs: list[tuple[str, str]] = [
        (a, b)
        for a in names
        for b in names
        if a != b and b not in allowed[a]
    ]
    out = [GENERATED_HEADER_INI, "[importlinter]\nroot_packages =\n"]
    for layer in arch.layers:
        root = _layer_module_root(layer.paths)
        if root:
            out.append(f"    {root}\n")
    out.append("\n")
    for a, b in forbidden_pairs:
        a_root = _layer_module_root(next(l.paths for l in arch.layers if l.name == a))
        b_root = _layer_module_root(next(l.paths for l in arch.layers if l.name == b))
        if not a_root or not b_root:
            print(
                f"warning: skipping contract {a}__to__{b} — could not derive a module root "
                f"(a_root={a_root!r}, b_root={b_root!r}). Layer paths must include a package "
                f"segment beyond just 'src/'.",
                file=sys.stderr,
            )
            continue
        out.append(
            f"[importlinter:contract:{a}__to__{b}]\n"
            f"name = {a} must not import {b}\n"
            f"type = forbidden\n"
            f"source_modules =\n    {a_root}\n"
            f"forbidden_modules =\n    {b_root}\n\n"
        )
    return "".join(out)


def _emit_pattern_py(pattern: Pattern, arch: Architecture) -> str:
    layer = next(l for l in arch.layers if l.name == pattern.layer)
    forbidden = list(pattern.forbidden_imports)
    globs = list(layer.paths)
    return (
        GENERATED_HEADER_PY
        + f"# Rule: {pattern.id} — forbids {forbidden!r} in layer {pattern.layer!r}\n"
        + "from __future__ import annotations\n"
        + "import pathlib\n"
        + "import re\n"
        + "import sys\n\n"
        + f"FORBIDDEN = {forbidden!r}\n"
        + f"GLOBS = {globs!r}\n"
        + f"RULE_ID = {pattern.id!r}\n\n"
        + "def main() -> int:\n"
        + "    root = pathlib.Path.cwd()\n"
        + "    pat = re.compile(r'(?:^|\\b)(?:import|from)\\s+(' + '|'.join(re.escape(n) for n in FORBIDDEN) + r')\\b')\n"
        + "    violations: list[str] = []\n"
        + "    seen: set[pathlib.Path] = set()\n"
        + "    def _files(p: pathlib.Path):\n"
        + "        if p.is_file():\n"
        + "            yield p\n"
        + "        elif p.is_dir():\n"
        + "            yield from p.rglob('*')\n"
        + "    for glob in GLOBS:\n"
        + "        for match in root.glob(glob):\n"
        + "            for path in _files(match):\n"
        + "                if not path.is_file() or path in seen:\n"
        + "                    continue\n"
        + "                seen.add(path)\n"
        + "                try:\n"
        + "                    text = path.read_text(encoding='utf-8')\n"
        + "                except (OSError, UnicodeDecodeError):\n"
        + "                    continue\n"
        + "                for lineno, line in enumerate(text.splitlines(), 1):\n"
        + "                    if pat.search(line):\n"
        + "                        violations.append(f\"{path}:{lineno}: {line.strip()}\")\n"
        + "    if violations:\n"
        + "        print(f\"arch-leash: rule {RULE_ID} violated:\")\n"
        + "        for v in violations:\n"
        + "            print(f\"  {v}\")\n"
        + "        return 1\n"
        + "    return 0\n\n"
        + "if __name__ == '__main__':\n"
        + "    raise SystemExit(main())\n"
    )


def _gates_without_arch_lines(text: str) -> list[str]:
    return [
        line for line in text.splitlines(keepends=False)
        if "# arch-leash:" not in line
    ]


def compile_architecture(root: pathlib.Path) -> None:
    arch_path = root / ".harness" / "architecture.yaml"
    arch = parse_architecture(arch_path.read_text(encoding="utf-8"))
    checks_dir = root / ".harness" / "checks"
    checks_dir.mkdir(parents=True, exist_ok=True)

    # Drop any previously-generated check files; we regenerate every time.
    for existing in checks_dir.glob("pattern-*.py"):
        if "GENERATED by scripts/harness/compile_architecture.py" in existing.read_text(encoding="utf-8"):
            existing.unlink()

    new_gate_lines: list[str] = []
    for pattern in arch.patterns:
        script_path = checks_dir / f"pattern-{pattern.id}.py"
        script_path.write_text(_emit_pattern_py(pattern, arch), encoding="utf-8")
        new_gate_lines.append(
            f"python .harness/checks/pattern-{pattern.id}.py  # arch-leash:{pattern.id}"
        )

    if _detect_python(root):
        ini_path = root / ".harness" / "importlinter.ini"
        ini_path.write_text(_emit_importlinter_ini(arch), encoding="utf-8")
        new_gate_lines.append(
            "python -m importlinter --config .harness/importlinter.ini  # arch-leash:py_edges"
        )

    gates_path = root / ".harness" / "gates"
    existing = gates_path.read_text(encoding="utf-8") if gates_path.exists() else "# Gates\n"
    kept = _gates_without_arch_lines(existing)
    if kept and kept[-1] != "":
        kept.append("")
    out = "\n".join(kept + new_gate_lines) + "\n"
    gates_path.write_text(out, encoding="utf-8")


def main() -> int:
    compile_architecture(pathlib.Path.cwd())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
